title: ZTronics
description: ESP32 and Arduino Tutorials

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

url: "https://ztronics.github.io"
baseurl: "/esp32-mpu6050-snake"

minimal_mistakes_skin: "dark"

search: true

logo: "/assets/images/logo.png"
