title: ZTronics Arduino Tutorials
description: ESP32, MPU6050 and Arduino tutorials

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: "https://ztronics.github.io"
baseurl: "/esp32-mpu6050-snake"

color_scheme: dark

search_enabled: true

heading_anchors: true

back_to_top: true

enable_copy_code_button: true
